app/blueprints/shop/models.py
from app import db
from datetime import datetime as dt

class Product(db.Model):
    id =db.Column(db.Integer, primary_key=True, unique=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    price = db.Column(db.Float)
    tax = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=dt.utcnow)
    date_updated = db.Column(db.DateTime)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def to_dict(self):
        data = {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'price': self.price,
            'tax': self.tax,
            'date_created': self.date_created,
            'date_updated': self.date_updated
        }
        return data

    def from_dict(self, data):
        for field in ['name', 'description', 'price']:
            if field in data:
                setattr(self, field, data[field])
        # setattr(self, 'tax', round(data[field] * 0.06),2)
        self.tax = round(self.price * 0.06,2)
 
    def __repr__(self):
        return f'<{self.name} @ {self.price}>'

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.ForeignKey('product.id'), nullable=False)
    date_added = db.Column(db.DateTime, default=dt.utcnow)
    
    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        from app.blueprints.auth.models import User
        return f'<Cart: {User.query.get({self.user_id}).email}: {Product.query.get(self.product_id).name}>'

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='/shop', static_folder='./static', template_folder='./templates')

from .import views, models

app/blueprints/shop/views.py
from .import bp as shop_bp
from flask import render_template, redirect, url_for, flash, request
from app.blueprints.shop.models import Product, Cart
from flask_login import current_user

@shop_bp.route('/')
def home():
    context = {
        'products': Product.query.all()
    }
    return render_template('shop/home.html', **context)

@shop_bp.route('/product/add')
def add_product():
    try:
        _id = request.args.get('id')
        p = Product.query.get(_id)
        c = Cart(user_id=current_user.id, product_id=p.id)
        c.save()
        flash(f'{p.name} was added successfully', 'success')
    except Exception as error:
        flash(f'{p.name} was not added successfully. Try again.', 'success')

    return redirect(url_for('shop.home'))

@shop_bp.route('/cart')
def cart():
    context = {}
    return render_template('shop/cart.html', **context)

app/blueprints/shop/templates/shop/cart.html
{% extends 'layout.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('shop.static', filename='css/shop.css') }}">
{% endblock %}


{% block content %}
    <h3>Cart</h3>
    <hr>

    <div class="table-responsive">
        <table class="table table-striped table-inverse ">
            <thead class="thead-inverse">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
                </thead>
                <tbody>
                    {% for p in cart['display_cart'] %}
                        <tr>
                            <td>{{ p['name'] }}</td>
                            <td>{{ p['description'] }}</td>
                            <td>{{ p['price'] }}</td>
                            <td>{{ p['quantity'] }}</td>
                        </tr>
                    {% endfor %}

                </tbody>
        </table>
    </div>
{% endblock %}

app/blueprints/shop/templates/shop/home.html
{% extends 'layout.html' %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('shop.static', filename='css/shop.css') }}">
{% endblock %}


{% block content %}
    <h3>Shop</h3>
    <hr>

    <div class="card-deck">
        {% for p in products %}
            <div class="col-md-4 product">
                <div class="card">
                    <div class="card-header">
                        <h6>
                            {{ p.name }}
                            <span class="float-right">${{ p.price }}</span>
                        </h6>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top" src="https://placedhold.it/500/500&image=Product" alt="{{ p.name }}">

                        <!-- <h4 class="card-title">{{ p.name }}</h4> -->
                        <p class="card-text">{{ p.description }}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{{ url_for('shop.add_product', id=p.id) }}" class="btn btn-success btn-block">Add to Cart</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}