app/blueprints/blog/models.py
from app import db
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login_manager



class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    date_created = db.Column(db.DateTime, nullable=False, default=dt.utcnow)
    date_updated = db.Column(db.DateTime, nullable=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    
    def __repr__(self):
        return f'<Post: {self.id} - ID: {self.body[10]}...>'

app/blueprints/shop/models.py
from app import db
from datetime import datetime as dt

class Product(db.Model):
    id =db.Column(db.Integer, primary_key=True, unique=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    price = db.Column(db.Float)
    tax = db.Column(db.Float)
    date_created = db.Column(db.DateTime, default=dt.utcnow)
    date_updated = db.Column(db.DateTime)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def to_dict(self):
        data = {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'price': self.price,
            'tax': self.tax,
            'date_created': self.date_created,
            'date_updated': self.date_updated
        }
        return data

    def from_dict(self, data):
        for field in ['name', 'description', 'price']:
            if field in data:
                setattr(self, field, data[field])
        # setattr(self, 'tax', round(data[field] * 0.06),2)
        self.tax = round(self.price * 0.06,2)
 
    def __repr__(self):
        return f'<{self.name} @ {self.price}>'

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.ForeignKey('product.id'), nullable=False)
    date_added = db.Column(db.DateTime, default=dt.utcnow)
    
    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        from app.blueprints.auth.models import User
        return f'<Cart: {User.query.get({self.user_id}).email}: {Product.query.get(self.product_id).name}>'

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config
from flask_moment import Moment
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
moment = Moment()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message = 'You do not have access to this page. Login in first please!'
login_manager.login_message_category = 'warning'

def create_app(config_class=Config): 
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)
    login_manager.init_app(app)

    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.blueprints.blog import bp as blog_bp
    app.register_blueprint(blog_bp)

    from app.blueprints.shop import bp as shop_bp
    app.register_blueprint(shop_bp)
    
    from app.blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)

    # Needs app context
    with app.app_context():
        # from app import views
        from .import context_processors

    from app import views

    return app

app/blueprints/api/__init__.py
from flask import Blueprint
from flask import Flask

bp = Blueprint('api', __name__, url_prefix='/api')

from .import views

app/blueprints/api/views.py
from .import bp as api_bp
from flask import jsonify, request
from app.blueprints.shop.models import Product
from app.blueprints.auth.models import User
from app import db
from datetime import datetime as dt

@api_bp.route('/shop', methods=['GET'])
def show_products():
    return jsonify([p.to_dict() for p in Product.query.all()])

@api_bp.route('/shop/product/<int:id>', methods=['GET'])
def get_product(id):
    return jsonify(Product.query.get(id).to_dict())

@api_bp.route('/shop/product/create', methods=['POST'])
def create_product():
    data = request.json
    p = Product()
    p.from_dict(data)
    p.save()
    return jsonify(p.to_dict()), 201

@api_bp.route('/shop/product/edit/<int:id>', methods=['PUT'])
def edit_product(id):
    data = request.json
    p = Product.query.get(id)
    p.from_dict(data)
    p.date_updated = dt.utcnow()
    db.session.commit()
    return jsonify(p.to_dict()), 201

@api_bp.route('/shop/product/delete/<int:id>', methods=['DELETE'])
def delete_product(id):
    product = Product.query.get(id)
    db.session.delete(product)
    db.session.commit()
    return jsonify([p.to_dict() for p in Product.query.all()])

app/blueprints/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog')

from .import models, views

app/blueprints/blog/views.py
from .import bp as blog_bp
from flask import request, flash, redirect, url_for
from .models import Post
from app import db
from flask_login import current_user

@blog_bp.route('/post/create', methods=['POST'])
def create_post():
    if request.method == 'POST':
        try:
            data = request.form['status_update']
            p = Post(body=data, user_id=current_user.id)
            print(p.__dict__)
            db.session.add(p)
            db.session.commit()
            flash('Post was created successfully', 'info')
        except:
            flash('There was an error creating your post. Try again.', 'danger')
    return redirect(url_for('main.home'))

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from .import models, views

app/blueprints/main/views.py
from app import db
from flask import render_template, request, redirect, url_for
from app.blueprints.auth.models import User
from app.blueprints.blog.models import Post
from flask_login import login_user, current_user, logout_user, login_required
from .import bp as main_bp
# from .import import send_email

@main_bp.route('/eddie')
def eddie():
    return render_template('eddie.html')

@main_bp.route('/')
def home():
    if current_user.is_authenticated:
        posts = current_user.followed_posts().all()
    else:
        posts = []
    context = {
        'user': current_user,
        'posts': posts
        # 'posts': Post.query.order_by(Post.date_created.desc()).all()
    }
    return render_template('home.html', **context)

@main_bp.route('/profile')
@login_required
def profile():
    context = {
        'posts': [p for p in Post.query.order_by(Post.date_created.desc()).all() if p.user_id == current_user.id]
    }
    return render_template('profile.html', **context)

@main_bp.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        form_data = {
            'name': request.form['name'],
            'email': request.form['email'],
            'budget': request.form['budget'],
            'message': request.form['message'],
        }
        send_email(form_data)
        flash('Thank you for your inquiry. We will contact you shortly!', 'primary')
    return render_template('contact.html')

@main_bp.route('/explore')
@login_required
def explore():
    context = {
        'users': [user for user in User.query.all() if current_user.id != user.id]
    }
    return render_template('explore.html', **context)

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='/shop', static_folder='./static', template_folder='./templates')

from .import views, models

app/blueprints/shop/views.py
from .import bp as shop_bp
from flask import render_template, redirect, url_for, flash, request
from app.blueprints.shop.models import Product, Cart
from flask_login import current_user

@shop_bp.route('/')
def home():
    context = {
        'products': Product.query.all()
    }
    return render_template('shop/home.html', **context)

@shop_bp.route('/product/add')
def add_product():
    try:
        _id = request.args.get('id')
        p = Product.query.get(_id)
        c = Cart(user_id=current_user.id, product_id=p.id)
        c.save()
        flash(f'{p.name} was added successfully', 'success')
    except Exception as error:
        flash(f'{p.name} was not added successfully. Try again.', 'success')

    return redirect(url_for('shop.home'))

@shop_bp.route('/cart')
def cart():
    context = {}
    return render_template('shop/cart.html', **context)

app/templates/contact.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Contact</h3>
    <hr>

    <form action="{{ url_for('main.contact') }}" method='POST'>
        <div class="form-group">
            <div class="form-group">
                <input type="text" class="form-control" name="name" placeholder="Type your name">
            </div>        
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Type your Email">
            </div>  
            <div class="form-group">
                <div class="form-group">
                    <select class="form-control" name="budget">
                        <option disabled selected>Choose a budget</option>

                        <option>$1,000</option>
                        <option>$2,000</option>
                        <option>$3,000+</option>
                    </select>
                </div>
            </div>  
            <div class="form-group">
                <textarea class="form-control" name="message" placeholder="Type a brief message..." rows="5"></textarea>
            </div>    
            <div class="form-group">
                <button class="btn btn-block btn-info">Send</button>   
            </div>    
        </div>
    </form>
{% endblock %}

app/templates/eddie.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Eddie</h3>
    <hr>

    <p>Welcome to my page!</p>
    
{% endblock %}

app/templates/explore.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Explore</h3>
    <hr>

    <div class='table-responsive'>
        <table class="table table-striped table-inverse">
            <thead class='thead-inverse'>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>(Un)Follow)</th>
                </tr>
            </thead>
            <tbody>
                {% for u in users %}
                    <tr>
                        <td>{{ u.first_name }}</td>
                        <td>{{ u.last_name }}</td>
                        <td>{{ u.email }}</td>
                        <td>
                            {% if not current_user.is_following(u) %}
                                <a href="{{ url_for('auth.follow', user_id=u.id) }}" class='btn btn-success'>Follow</a>
                            {% else %}
                                <a href="{{ url_for('auth.unfollow', email=u.email )}}" class='btn btn-warning'>Unfollow</a>
                            {% endif %}                            
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    <h3>
        Home
        {% if current_user.is_authenticated %}
            <span class='float-right'>Hello, {{ user.first_name }}!</span>
        {% else %}
            <span class='float-right'>Gooday!</span>
        {% endif %}

    </h3>
    <hr>

    <form action="{{ url_for('blog.create_post') }}" method='POST'>
        <div class="form-group">
            <div class='row'>
                <div class='col-md-11'>
                    <div class='input-group'>
                        <input type="text" name="status_update" class="form-control" placeholder="What's on your mind?"/>
                    </div>
                </div>
                <div class='col-md-1'>
                    <div class='input-group'>
                        <input type="submit" class="btn btn-primary" value="Post"/>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% if posts %}
        <ul class="list-group">
            {% for p in posts %}
            <li class="list-group-item">
                <h4>
                    {{ p['title'] }}
                    <span style="font-size: 15px; color: gray;" class='float-right'>{{ moment(p.date_created).fromNow() }}</span>
                </h4>
                <p>{{ p['body'] }}</p>
                <cite>&mdash; {{ p.user.email }}</cite>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>
            You need to log in to view posts.
        </p>
    {% endif %}

{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block styles %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Import Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}

  </head>
  <body>
      
    <header>
        {% include './partials/navigation.html' %}
    </header>

    {% include './partials/flash_messages.html' %}

    <main class='container'>
        {% block content %}
        {% endblock %}
    </main>

    <footer>

    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {{ moment.include_moment() }}

  </body>
</html>

app/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Login</h3>
    <hr>

    <div class='col-md-6'>
        <form action="{{ url_for('auth.login') }}" method='POST'>
            <div class="form-group">
                <input type="text" name="email" class='form-control' placeholder='Email'>
            </div>

            <div class="form-group">
                <input type="password" name="password" class='form-control' placeholder='Pasword'>
            </div>

            <input type="submit" value='Submit' class='btn btn-info btn-block'>
        </form>
    </div>

{% endblock %}

app/templates/partials/flash_messages.html
<div class='container'>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for c, m in messages %}
                <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{ m }}</strong> 
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>

app/templates/partials/navigation.html
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('main.eddie') }}">Eddie</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.profile') }}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
            </li>

            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.explore') }}">Explore</a>
                </li>


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownId">
                        <a class="dropdown-item" href="{{ url_for('shop.home') }}">Products</a>
                        <a class="dropdown-item" href="{{ url_for('shop.cart') }}">
                            Cart
                            <span class="float-right">
                                <span class="badge badge-secondary bg-lg">{{ cart['items']|length }}</span>
                            </span>
                        </a>
                        <a class="dropdown-item" href="#">Checkout</a>
                    </div>
                </li>
            {% endif %}

        </ul>

        <ul class='navbar-nav m1-auto'>
            {% if not current_user.is_authenticated %}
            <li class='nav-item'>
                <a href="{{ url_for('auth.login') }}" class='nav-link'>Login</a>
            </li>
            <li class='nav-item'>
                <a href="{{ url_for('auth.register') }}" class='nav-link'>Register</a>
            </li>
            {% else %}
            <li class='nav-item'>
                <a href="{{ url_for('auth.logout') }}" class='nav-link'>Logout</a>
            </li>
            {% endif %}

        </ul>
        
    </div>
</nav>

app/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Profile</h3>
    <hr>

    <div class="col-md-6">
        <form action="{{ url_for('auth.update_user') }}" method='POST'>
            <div class="row">
                <div class="col-md-6 standardized">
                    <div class="form-group">
                        <input type="text" name="first_name" class="form-control" placeholder="First Name" value="{{ current_user.first_name }}">
                    </div>
                </div>
                <div class="col-md-6 standardized">
                    <div class="form-group">
                        <input type="text" name="last_name" class="form-control" placeholder="Last Name" value="{{ current_user.last_name }}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 standardized">
                    <div class="form-group">
                        <input type="text" name="email" class="form-control" placeholder="Email" value="{{ current_user.email }}">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 standardized">
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                </div>
                <div class="col-md-6 standardized">
                    <div class="form-group">
                        <input type="password" name="confirm_password" class="form-control" placeholder="Confirm Password">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 standardized">
                    <div class="form-group">
                        <button type="submit" class="btn btn-info btn-block">Update Information</button>
                    </div>
                </div>
            </div>      
        </form>
    </div>

    <hr>


    <form action="{{ url_for('blog.create_post') }}" method='POST'>
        <div class="form-group">
            <div class='row'>
                <div class='col-md-11'>
                    <div class='input-group'>
                        <input type="text" name="status_update" class="form-control" placeholder="What's on your mind?"/>
                    </div>
                </div>
                <div class='col-md-1'>
                    <div class='input-group'>
                        <input type="submit" class="btn btn-primary" value="Post"/>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <ul class="list-group">
        {% for p in posts %}
        <li class="list-group-item">
            <h4>
                {{ p['title'] }}
                <span style="font-size: 15px; color: gray;" class='float-right'>{{ moment(p.date_created).fromNow() }}</span>
            </h4>
            <p>{{ p['body'] }}</p>
            <cite>&mdash; {{ p.user.email }}</cite>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/register.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Register</h3>
    <hr>

    <div class='col-md-6'>
        <form action="{{ url_for('auth.register') }}" method='POST'>
            <div class="form-group">
                <input type="text" name="first_name" class='form-control' placeholder='First Name'>
            </div>

            <div class="form-group">
                <input type="text" name="last_name" class='form-control' placeholder='Last Name'>
            </div>

            <div class="form-group">
                <input type="password" name="password" class='form-control' placeholder='Pasword'>
            </div>

            <div class="form-group">
                <input type="password" name="confirm_password" class='form-control' placeholder='Confirm Pasword'>
            </div>

            <input type="submit" value='Submit' class='btn btn-info btn-block'>
            <!-- <button class='btn btn-info btn-block' type='submit'>Submit</button> -->
        </form>
    </div>
{% endblock %}